//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class stopat
    {
        public short TID { get; set; }
        public short SID { get; set; }
        public bool Direction { get; set; }
        public System.TimeSpan Atime { get; set; }
        public System.TimeSpan Dtime { get; set; }
    
        public virtual station station { get; set; }
        public virtual train train { get; set; }
    }
}
