//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public byte UID { get; set; }
        public string Name { get; set; }
        public string Uname { get; set; }
        public string Password { get; set; }
    }
}
