// <auto-generated />
namespace pro_web_a.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetrain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetrain));
        
        string IMigrationMetadata.Id
        {
            get { return "201904280512590_updatetrain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
