//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro_web_a.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDBContext : DbContext
    {
        public ProjectDBContext()
            : base("name=ProjectDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<stopat> stopats { get; set; }
        public virtual DbSet<train> trains { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
