//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro_web_a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public station()
        {
            this.stopats = new HashSet<stopat>();
        }
    
        public short SID { get; set; }
        public string Name { get; set; }
        public double Distance { get; set; }
        public double Llongitude { get; set; }
        public double Llatitude { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public short RID { get; set; }
    
        public virtual route route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stopat> stopats { get; set; }
    }
}
