//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public byte DID { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Locationdata { get; set; }
    
        public virtual device device { get; set; }
    }
}
