//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public short TID { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<System.TimeSpan> Stime { get; set; }
        public Nullable<System.TimeSpan> Etime { get; set; }
        public Nullable<double> Maxspeed { get; set; }
        public Nullable<double> Avgspeed { get; set; }
        public Nullable<System.TimeSpan> Delay { get; set; }
    
        public virtual train train { get; set; }
    }
}
